version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8081:80"  
    volumes:
      - ./src:/var/www/html  # Sincroniza os arquivos PHP da pasta src
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: crud_base
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d # Monta a pasta com o SQL dump

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8082:80"  # PhpMyAdmin acessível na porta 8080

volumes:
  db_data:
